name: cantara
version: '2.3.1'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: strict
icon: app.cantara.Cantara.png
base: core20
grade: stable

architectures:
  - build-on: [amd64, arm64]

parts:
  cantara:
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - fpc
    - lazarus
    - lcl
    - lcl-utils
    - build-essential
    - libqt5pas-dev
    - libqt5pas1
    stage-packages:
    - libqt5pas1
    #- libatk1.0-0
    #- libgtk2.0-0
    - libxinerama1
    override-build: |
      lazbuild -B --bm="Release" --ws="qt5" Cantara.lpi
      cp -r languages $SNAPCRAFT_PART_INSTALL/
      install cantara $SNAPCRAFT_PART_INSTALL/
      install cantara.desktop $SNAPCRAFT_PART_INSTALL/
      install Cantara.ico $SNAPCRAFT_PART_INSTALL/
      install app.cantara.Cantara.png $SNAPCRAFT_PART_INSTALL/
    stage:
    - lib
    - usr
    - etc
    - cantara
    - languages
    - cantara.desktop
    - Cantara.ico
    - app.cantara.Cantara.png
  cleanup:
    after: [cantara]
    plugin: nil
    build-snaps: [kde-frameworks-5-91-qt-5-15-3-core20]
    override-prime: |
      set -eux
      for snap in "kde-frameworks-5-91-qt-5-15-3-core20"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for cruft in bug lintian man icons; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$cruft
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
      find $SNAPCRAFT_PRIME/usr/lib -type f,l -name 'libQt*.so*' ! -name 'libQt5Pas*.so*' -delete

apps:
  cantara:
    extensions:
      - kde-neon
    command: cantara
    desktop: cantara.desktop
    plugs:
    - home
    - opengl
    - desktop
    - desktop-legacy
    - x11
    - unity7
